### ISSUE TITLE
Failed to exit

### ISSUE THREAD

**Issue by xu405049495** [chnejohnson/vue-dapp#83] opened 2022-10-01 14:59 UTC
in  the page  i click button to exit the metamask . call the method disconnect from  useWallet. but  the  isActivated from useEthers  is true . i think  the isActivated  will be false .Did I understand it wrong?

**Comment by chnejohnson** [comment] 2022-10-11 16:26
Right, when using MetaMask, the user can click disconnect on the page but it will do nothing except for the button text change because MetaMask doesn't support programmatic disconnect (#62)

Besides, MetaMask's disconnect event would be triggered when some chain changed. So I exclude the disconnect function when using MetaMask.

https://github.com/chnejohnson/vue-dapp/blob/650b021d3834fece88309b63781a2fe6369fda23/src/composables/useWallet.ts#L89-L99

**Comment by chnejohnson** [comment] 2022-10-12 00:19
But I found a problem related to what you refer to, the isActivated is still false when the onActivated being triggered.
```js
// vue-dapp/demo/src/App.vue

onActivated(() => {
  selectedChainId.value = chainId.value as number
  console.log(isActivated.value)          // return false when the wallet is connected
})
```

**Comment by chnejohnson** [comment] 2022-10-16 15:15
@xu405049495 please give me more information about how to reproduce your situation, or I will close this issue.

**Closed** 2022-10-26 14:19 UTC
