### ISSUE TITLE
disconnect() doesn't fire in sample code

### ISSUE THREAD

**Issue by str11ngfello** [chnejohnson/vue-dapp#62] opened 2022-06-27 19:27 UTC
disconnect from useWallet doesn't fire in my app. I reproduced this in the sample code just now. 

To repro: 
1) Download latest
2) yarn && yarn dev
3) connect to metamask
4) press blue disconnect button observe no console.log that says 'disconnect'

However, changing network does fire the change event.

Metamask is still connected after pressing disconnect. (which I figured it would be since the callback didn't fire)

https://user-images.githubusercontent.com/877000/176020803-1bb9f9e2-3875-4157-9b56-1ded2ed76c60.mov

**Comment by re2005** [comment] 2022-06-28 13:38
This may is not suppose to happen, You simply disconnecting your page from the Metamask, but not Metamask from your domain. Don't get confused here.

**Comment by chnejohnson** [comment] 2022-07-07 15:22
FYI
- https://github.com/MetaMask/metamask-extension/issues/10353 

https://github.com/chnejohnson/vue-dapp/blob/4df55dbef7623db411992c8d2c31846242c9233e/src/wallets/metaMask.ts#L114-L132

**Comment by frankye23** [comment] 2022-12-14 09:56
I also run into the problem that when i call disconnet, isActivated seem to be false.But when i refresh the page,i still got my wallet address. Also I just checkout websites like opensea and uniswap, when i hit disconnect button, I DO disconnect my wallet from the website. I wonder what you mean by "MetaMask doesn't support programmatic disconnect"?

**Comment by re2005** [comment] 2022-12-14 10:23
@frankye23 did you setup the `autoConnect` to true ?

@chnejohnson I think other libs are storing a flag on `localStorage` something like `autoConnect` false.

**Comment by chnejohnson** [comment] 2022-12-14 11:37
> I wonder what you mean by "MetaMask doesn't support programmatic disconnect"?

@frankye23  I mean the Connected status on MetaMask. If you have been connected, it would stay connected even if the web app seems disconnected.

![截圖 2022-12-14 下午7 25 11](https://user-images.githubusercontent.com/31992185/207583006-f1b53eed-028c-418b-b088-a2e3402b54c7.png)

@re2005 So if the user has clicked the disconnect button, it should not trigger auto connect when he refreshed the window, right?

**Comment by re2005** [comment] 2022-12-14 13:43
Yes, @chnejohnson I'm wondering if this is accepted/expected behaviour? What do you think ?

On `Uniswap`, even when you have disconnected, after refresh the page it still connects automatically. So maybe we should not worry about it for now. But is something to think about. If an user deliberately, click to `disconnect` we could save that and even if the app has the `autoConnect` set to true, we would ignore it.

Cheers

**Comment by chnejohnson** [comment] 2022-12-15 01:49
Cool, maybe we can add an option for users to control this feature?

Hmm, when I tested on Uniswap, it doesn't connect automatically after I refresh the page 🤔

https://user-images.githubusercontent.com/31992185/207753304-05e2a38a-172f-48e2-9194-31e9d3bd6ef8.mov

**Comment by frankye23** [comment] 2022-12-15 06:34
> did you setup the `autoConnect` to true ?

Yes, i did. The reason is that  i want to stay connected when i refresh my pages .But i also would like it stay disconnected after i click disconnect and refresh my page.

**Comment by re2005** [comment] 2022-12-15 11:40
@chnejohnson Maybe we can introduce this new flag, `persistDisconnect` and if that is true, we store on `localStorage` to not `autoConnect` after refresh.

Looking to [Uniswap](https://app.uniswap.org/), look at this: 

https://user-images.githubusercontent.com/2920357/207850265-685681b3-151a-43b9-b610-61a1ce06f74a.mov

Connected and after refresh, connected again :\

**Comment by chnejohnson** [comment] 2022-12-15 15:10
> Maybe we can introduce this new flag, persistDisconnect and if that is true, we store on localStorage to not autoConnect after refresh.
Nice!

> Connected and after refresh, connected again :\
I found the problem, you can't reload the page too quickly, wait a second then refresh 😆

**Comment by re2005** [comment] 2022-12-16 17:56
> I think this is more reasonable than the existing implementation, maybe we should setup `persistDisconnect` default to true if the user setup the autoConnect to true?

Agreed! I believe to be a concise behaviour.

We should also document it.

Thanks @chnejohnson

**Comment by chnejohnson** [comment] 2022-12-22 10:15
Fixed in v0.6.3

**Closed by chnejohnson** 2022-12-22 10:15 UTC
